name: alerts
on:
  workflow_run:
    workflows:
      - Node.js CI
    types:
      - completed
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Dump env
      env:
        ENV_JSON: ${{ toJson(env) }}
      run: |
        echo "$ENV_JSON"

    - name: Call BrakeCODE API
      run: |
        curl -k -L https://8w1i.ngrok-dns.june07.com/api/v1/alert?appId=alerts \
          -H 'Content-Type: application/json' \
          -H "x-api-key: { \"apikey\": \"${{ secrets.BRAKECODE_API_KEY }}\" }" \
          -d "{\"payload\": {\"topic\": \"notification\", \"title\": \"GitHub workflow completed.\", \"content\": \"\"}}"
