name: alerts
on:
  workflow_run:
    workflows:
      - Node.js CI
    types:
      - completed
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:

    - name: Call BrakeCODE API
      run: |
        curl -k -L https://8w1i.ngrok-dns.june07.com/api/v1/alert?appId=alerts \
          -H 'Content-Type: application/json' \
          -H "x-api-key: { \"apikey\": \"${{ secrets.BRAKECODE_API_KEY }}\" }" \
          -d '{"message":"workflow completed."}'
